package config

// Version is the current config schema version.
// v4 is a fresh start: the mihomo-era fields (source/traffic/runtime.tun)
// are gone; egress is either direct or a single upstream proxy.
const Version = 4

// Egress modes.
const (
	EgressDirect = "direct"
	EgressProxy  = "proxy"
	RouteReject  = "reject"
)

const (
	RuleDomain       = "domain"
	RuleDomainSuffix = "domain-suffix"
	RuleIPCIDR       = "ip-cidr"
	RuleSrcIP        = "src-ip"
)

// Upstream proxy kinds.
const (
	ProxyTypeHTTP   = "http"
	ProxyTypeSOCKS5 = "socks5"
)

// Config is the root of gateway.yaml.
type Config struct {
	Version   int           `yaml:"version"`
	Gateway   GatewayConfig `yaml:"gateway"`
	Egress    EgressConfig  `yaml:"egress"`
	Routing   RoutingConfig `yaml:"routing,omitempty"`
	DNS       DNSConfig     `yaml:"dns"`
	QUICBlock bool          `yaml:"quic_block"`
	Runtime   RuntimeConfig `yaml:"runtime"`
}

// RoutingConfig overrides the default egress for matching domains.
type RoutingConfig struct {
	Rules []RoutingRule `yaml:"rules,omitempty" json:"rules"`
}

type RoutingRule struct {
	Type   string `yaml:"type" json:"type"`
	Value  string `yaml:"value" json:"value"`
	Action string `yaml:"action" json:"action"`
	// Group is display-only metadata for clustering rules in editors;
	// matching stays a flat ordered list.
	Group string `yaml:"group,omitempty" json:"group,omitempty"`
	// Learned marks rules generated by proxy→direct fallback auto-learning,
	// so the UI can badge them and the user can delete them with confidence.
	Learned bool `yaml:"learned,omitempty" json:"learned,omitempty"`
}

// GatewayConfig controls LAN device onboarding.
type GatewayConfig struct {
	Enabled bool `yaml:"enabled"`
}

// EgressConfig decides where relayed traffic exits.
type EgressConfig struct {
	Mode  string      `yaml:"mode"` // direct | proxy
	Proxy ProxyConfig `yaml:"proxy"`
}

// ProxyConfig is the single upstream proxy used when Mode=proxy.
// Users who need protocols (VLESS/...) run their own clash/sing-box and
// point this at its local mixed port.
type ProxyConfig struct {
	Type     string `yaml:"type"` // http | socks5
	Host     string `yaml:"host"`
	Port     int    `yaml:"port"`
	Username string `yaml:"username,omitempty"`
	Password string `yaml:"password,omitempty"`
}

// DNSConfig controls the LAN DNS service.
type DNSConfig struct {
	Enabled      bool     `yaml:"enabled"`
	Port         int      `yaml:"port"`
	Upstreams    []string `yaml:"upstreams"`
	FakeIP       bool     `yaml:"fake_ip"`        // forced on in proxy mode (see Normalize)
	Hijack       bool     `yaml:"hijack"`         // intercept LAN traffic to any :53
	FakeIPFilter []string `yaml:"fake_ip_filter"` // extra suffixes that resolve for real
}

// RuntimeConfig holds ports and logging.
type RuntimeConfig struct {
	RedirPort   int    `yaml:"redir_port"`
	APIPort     int    `yaml:"api_port"` // 127.0.0.1-only status API
	LogLevel    string `yaml:"log_level"`
	FakeIPRange string `yaml:"fake_ip_range"`
}

// Default returns the recommended v4 configuration.
func Default() *Config {
	return &Config{
		Version: Version,
		Gateway: GatewayConfig{
			Enabled: true,
		},
		Egress: EgressConfig{
			Mode: EgressDirect,
			Proxy: ProxyConfig{
				Type: ProxyTypeSOCKS5,
				Host: "127.0.0.1",
				Port: 7897,
			},
		},
		DNS: DNSConfig{
			Enabled:   true,
			Port:      53,
			Upstreams: []string{"223.5.5.5", "119.29.29.29"},
			FakeIP:    true,
			Hijack:    false,
		},
		QUICBlock: true,
		Runtime: RuntimeConfig{
			RedirPort:   17892,
			APIPort:     19090,
			LogLevel:    "info",
			FakeIPRange: "198.18.0.0/16",
		},
	}
}
